### ISSUE TITLE
dialog popover

### ISSUE THREAD

**Issue by shujianbu** [shujianbu/DJToolboxes#1]
Tasks:
1. "Info" button alignment 
2. add github link to this repo
3. popover dialog content and styling (content can be used for this ABOUT? in chinese?)

@hylbyj

**Comment by hylbyj** [comment]
Few questions:
1. add github link to this repo? which link? 
2. do we have text for about section and I could come up with styling?

**Comment by shujianbu** [comment]
1. https://github.com/shujianbu/DJToolboxes for now. later will migrate the account. - cuz this website will be hosted under djchina.org, it won't be in this github.io page.
2. not yet... lol... almost there..

**Comment by hylbyj** [comment]
where i can find "info" button image?

**Comment by shujianbu** [comment]
there's no image. It's just a button now, plain text works, but you can use it from http://www.material-ui.com/#/components/font-icon

**Comment by shujianbu** [comment]
any updates? can you add the readme content as well? you can refer to the DJShowcase one

**Comment by hylbyj** [comment]
I'll update it tonight :)

**Comment by shujianbu** [comment]
I've updated the content, plan to update to the website tonight
