### ISSUE TITLE
media css

### ISSUE THREAD

**Issue by shujianbu** [shujianbu/DJToolboxes#2]
Add rules for @media
i.e. when we go pad size or mobile size, need to change the css. refer to: https://github.com/shujianbu/DJShowcases/blob/master/app%2Fmain.css

**Comment by hylbyj** [comment]
Sent out a pull request

**Comment by shujianbu** [comment]
should we hide the whole nav section in mobile view? Also, each storyboard height looks a bit off?

**Comment by hylbyj** [comment]
Thanks! thought of changing the height. it'd be better to hide whole nav section in mobile view, will work on both today.

**Comment by shujianbu** [comment]
new the change looks good. The first tool "2014-06-bikeshare-gender-maps by buzzfeednews" text is too long.. under mobile view, the text can wrap with ellipsis?
