### ISSUE TITLE
what to do with each tool's description?

### ISSUE THREAD

**Issue by shujianbu** [shujianbu/DJToolboxes#5]
@HaoyunS should we add the description on hover? any design ideas?

**Comment by shujianbu** [comment]
@hylbyj can you try if you can make the hover work?

**Comment by hylbyj** [comment]
yep, working on that

**Comment by hylbyj** [comment]
<img width="1097" alt="screen shot 2016-03-30 at 9 17 04 pm" src="https://cloud.githubusercontent.com/assets/5619319/14165341/ce002fa8-f6bc-11e5-91e1-36dda083a502.png">

**Comment by hylbyj** [comment]
mobile look: 
<img width="373" alt="screen shot 2016-03-30 at 9 18 03 pm" src="https://cloud.githubusercontent.com/assets/5619319/14165361/f86316a2-f6bc-11e5-9a46-6b5e55f585fc.png">

**Comment by shujianbu** [comment]
click positions shift on desktop? mobile works great..

**Comment by shujianbu** [comment]
just saw it's been fixed! XD
